### ISSUE TITLE
Erase on PostgreSQL with ltree extension

### ISSUE THREAD

**Issue by bchavez** [lecaillon/Evolve#128]
I have:
* `CREATE EXTENSION plv8`
* `CREATE EXTENSION IF NOT EXISTS ltree`

in my PostgreSQL DB, but when I ask `Evolve` to `.Erase()`, I get the following error message:

```
Evolve.EvolveException
  HResult=0x80131500
  Message=Erase failed. Impossible to erase schema public. 2BP01: cannot drop type ltree because extension ltree requires it Sql query: DROP TYPE IF EXISTS "public"."ltree" CASCADE 2BP01: cannot drop type ltree because extension ltree requires it
  Source=Evolve
  StackTrace:
   at Evolve.Evolve.InternalErase(DatabaseHelper db)
   at Evolve.Evolve.InternalExecuteCommand(Action`1 commandAction)
   at PROJECT.Migrations.SchemaExporter.erase() in C:\Code\Projects\PROJECT_CLOUDN\PROJECT.Migrations\SchemaExporter.cs:line 52

Inner Exception 1:
EvolveSqlException: 2BP01: cannot drop type ltree because extension ltree requires it Sql query: DROP TYPE IF EXISTS "public"."ltree" CASCADE 2BP01: cannot drop type ltree because extension ltree requires it

Inner Exception 2:
PostgresException: 2BP01: cannot drop type ltree because extension ltree requires it
```

I'm guessing there's something wrong with the erase procedure that is tied to `ltree` somehow.

This was tested on PostgreSQQL 10.7.1. I used the binaries found here:

https://www.nuget.org/packages/PostgreSql.Binaries.Lite.Plv8/10.7.1

**Comment by lecaillon** [comment]
Hard time reproducing your issue. I've just refactored the `Erase` command for PostgreSQL. Should be fine in Evolve 2.3
Feel free to give me feedback about it.
