### ISSUE TITLE
Can not run Evolve for MSSqlLocaldb

### ISSUE THREAD

**Issue by rustamkulenov** [lecaillon/Evolve#66]
I'm trying to run evolve for SQL Server Express [LocalDB](https://docs.microsoft.com/ru-ru/sql/database-engine/configure-windows/sql-server-2016-express-localdb?view=sql-server-2017).
My config file: 
```
<add key="Evolve.ConnectionString" value="Data Source=(localdb)\MSSQLLocalDB;Database=backoffice;Integrated Security=True;Connect Timeout=30;" />
<add key="Evolve.Driver" value="SqlClient" />
<add key="Evolve.Locations" value="migrations" />
<add key="Evolve.Command" value="migrate" />
```
In msbuild mode I receive an error:

```
1>  Executing Migrate...
1>  Evolve initialized.
1>  Mark schema dbo as empty.
1>  No metadata found.
1>Evolve : error : EvolveSqlException: Cannot release the application lock (Database Principal: 'public', Resource: 'Evolve') because it is not currently held. Sql query: sp_releaseapplock Cannot release the application lock (Database Principal: 'public', Resource: 'Evolve') because it is not currently held.
1>Evolve : error :    at Evolve.WrappedConnectionEx.Execute[T](WrappedConnection wrappedConnection, String sql, Func`2 query, Action`1 setupDbCommand)
1>Evolve : error :    at Evolve.WrappedConnectionEx.ExecuteDbCommand[T](WrappedConnection wrappedConnection, String sql, Action`1 setupDbCommand, Func`2 query)
1>Evolve : error :    at Evolve.Dialect.SQLServer.SQLServerDatabase.ReleaseApplicationLock()
1>Evolve : error :    at Evolve.Evolve.InternalExecuteCommand(Action`1 commandAction)
1>Evolve : error :    at Evolve.Evolve.Migrate()
1>Evolve : error :    at Evolve.Evolve.ExecuteCommand()
1>Evolve : error :    at Evolve.MsBuild.EvolveBoot.Execute()
1>Evolve : error : SqlException: Cannot release the application lock (Database Principal: 'public', Resource: 'Evolve') because it is not currently held.
1>Evolve : error :    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
1>Evolve : error :    at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
1>Evolve : error :    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
1>Evolve : error :    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
1>Evolve : error :    at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
1>Evolve : error :    at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
1>Evolve : error :    at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
1>Evolve : error :    at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
1>Evolve : error :    at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
1>Evolve : error :    at Evolve.Dialect.SQLServer.SQLServerDatabase.<>c.<ReleaseApplicationLock>b__11_1(IDbCommand cmd)
1>Evolve : error :    at Evolve.WrappedConnectionEx.Execute[T](WrappedConnection wrappedConnection, String sql, Func`2 query, Action`1 setupDbCommand)
```

Is MS SQL Server Express LocalDB not supported or I'm doing something wrong?

**Comment by rustamkulenov** [comment]
I've found the reason. This error happens because of this code in SQL migration. I removed it and now everything works as expected.
```
USE [master]
GO
ALTER DATABASE [${database}] SET  READ_WRITE 
```
