### ISSUE TITLE
Exception Using Postgres new Driver 4.0.x

### ISSUE THREAD

**Issue by guy-lud** [lecaillon/Evolve#70]
Hey, 

I've tried using Evolve (which is great) with the new version of Prostgres version driver 4.0.x and i get an exception while trying to execute scan.l file with the statement `SHOW VARIABLES LIKE '%.

**Comment by lecaillon** [comment]
Hi, it seems there are breaking changes around the new npgsql 4.0.
I must investigate how to make Evolve compatible with it. 
Hope to find time soon and release something before end of august

**Comment by guy-lud** [comment]
Thank you

**Comment by lecaillon** [comment]
Can you please give me some insights ? Is the example you gave me worked with the Npgsql 3.x ?
What do you try to achieve ?
What version of the .NET project do you run ?

**Comment by guy-lud** [comment]
Hi @lecaillon ,
Yes the project works on Npgsql 3.x when upgrading t 4.X an exception is thrown with the message above.
I'll try top post the exact message ASAP. + the project is running on Core 2.1

**Comment by guy-lud** [comment]
Hey,
Took sometime, sorry about that.

This is the exception i am getting, does it help ?

Npgsql.PostgresException: 42601: syntax error at or near "LIKE"
  at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:1012
  at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:1032
  at at System.Threading.Tasks.ValueTask`1.get_Result()
  at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming) in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:444
  at Npgsql.NpgsqlDataReader.NextResult() in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:332
  at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:1219
  at at System.Threading.Tasks.ValueTask`1.get_Result()
  at Npgsql.NpgsqlCommand.ExecuteScalar(Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:1084
  at at System.Threading.Tasks.ValueTask`1.get_Result()
  at Npgsql.NpgsqlCommand.ExecuteScalar() in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:1061
  at at Evolve.WrappedConnectionEx.<>c.<QueryForString>b__3_0(IDbCommand cmd)
  at at Evolve.WrappedConnectionEx.Execute[T](WrappedConnection wrappedConnection, String sql, Func`2 query, Action`1 setupDbCommand)

**Comment by guy-lud** [comment]
The problem returns on version 1.9 :(

Npgsql.PostgresException: 42601: syntax error at or near "LIKE"
  at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:1012
  at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:1032
  at at System.Threading.Tasks.ValueTask`1.get_Result()
  at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming) in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:444
  at Npgsql.NpgsqlDataReader.NextResult() in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:332
  at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:1219
  at at System.Threading.Tasks.ValueTask`1.get_Result()
  at Npgsql.NpgsqlCommand.ExecuteScalar(Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:1084
  at at System.Threading.Tasks.ValueTask`1.get_Result()
  at Npgsql.NpgsqlCommand.ExecuteScalar() in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:1061
  at at Evolve.WrappedConnectionEx.<>c.<QueryForString>b__6_0(IDbCommand cmd)
  at at Evolve.WrappedConnectionEx.Execute[T](WrappedConnection wrappedConnection, String sql, Func`2 query, Action`1 setupDbCommand)

Any news ?

**Comment by lecaillon** [comment]
I do not reproduce this behavior. Can you give me a lot more info please. 
Describe the platform, the database version, the migration script that fails and/or when it fails. Do you use Evolve at build time or directly in your code ? Is it every time you start Evolve ...

**Comment by guy-lud** [comment]
Are you using the new Postgres Driver >= 4.0.0 ?

**Comment by lecaillon** [comment]
Yes, in several projects

**Comment by guy-lud** [comment]
I've created a new program with only this code
````
string connectionString = $"Username=admin;" +
			                          $"Password=admin;" +
			                          $"Host=localhost;" +
			                          $"Port=5432;" +
			                          $"Database=test_database;";

			using (var cn = new Npgsql.NpgsqlConnection(connectionString))
			{
				var evolve = new Evolve.Evolve(cn)
				{
					Locations = new[] {"./"},
					MustEraseOnValidationError = true,
					IsEraseDisabled = true,
					MetadataTableName = "DB_VERSION",
					Schemas = new[] {"public"},
					Command = CommandOptions.Migrate,
					EnableClusterMode = true,
					StartVersion = new MigrationVersion("1.0.0")
				};

				try
				{
					evolve.Migrate();
				}
				catch (EvolveException e)
				{

				}
			}
		}
````

When starting the program i still get this exception, 

the version of the database is 9.6.8 (linux both DB and Application)

**Comment by guy-lud** [comment]
The Script folder is empty, this is while creating evolve version table IMO

**Comment by lecaillon** [comment]
I do not reproduce your behavior testing exactly your snippet on Windows, .NET Core 2.1, with an empty PostgreSQL 9.6 (Docker image: 9.6-alpine)

Have you got by any chance an inner exception, because the one  you paste seems incomplete to me. Or can you test on Windows to see if you have the same behavior ?

**Comment by guy-lud** [comment]
Looks like an inner exception that you are catching inside ?

![image](https://user-images.githubusercontent.com/10279653/49375915-4c822300-f70e-11e8-9532-2fb60a9d3ae0.png)

![image](https://user-images.githubusercontent.com/10279653/49375963-6de30f00-f70e-11e8-9563-a4272148007d.png)

**Comment by guy-lud** [comment]
Ok i've got an idea, 
Some how i am getting this exception 
````
 public static DBMS GetDatabaseServerType(this WrappedConnection wrappedConnection)
        {
            string dbVersion = null;

            try
            {
                dbVersion = QueryForString(wrappedConnection, "SHOW VARIABLES LIKE '%version%';");
                if (!dbVersion.IsNullOrWhiteSpace())
                {
                    return DBMS.MySQL_MariaDB;
                }
            }
            catch { }

            try
            {
                dbVersion = QueryForString(wrappedConnection, "SELECT version()"); // attention ca marche aussi pour mysql
                if (!dbVersion.IsNullOrWhiteSpace()) 
                {
                    return DBMS.PostgreSQL;
                }
            }
            catch { }
````

and by using Rider (not VS) is away of that and stopping my debugger.

**Comment by lecaillon** [comment]
So it seems to be this request that causes the issue in your case ?

> SHOW VARIABLES LIKE '%version%';

It is the only one in Evolve with the "LIKE" keyword I think, so it could explain the error message.
Can you execute it on you database to see if it works ?

**Comment by guy-lud** [comment]
sql> SHOW VARIABLES LIKE '%version%'
[2018-12-04 12:01:29] [42601] ERROR: syntax error at or near "LIKE"
[2018-12-04 12:01:29] Position: 16

So yes .. this explains it, and Rider is throwing this exception at me even while an existing catch phrase. 

So all is well in the land of evolve .. yet postgres logs are filled with "ERROR: syntax error at or near "LIKE"" :(

I think that Dapper is verifying what Driver is used by the .Net driver name. 

Anyway thanks for your help.

**Comment by ohadab29** [comment]
hi 
cam to the same issue :(
- so i can not use Postgres DB with Evolve ?
